services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"



volumes:
  postgres_data:

networks:
  my_network:
